name: .NET Core

on: workflow_dispatch

permissions:
      id-token: write
      contents: read

env:
  AZURE_WEBAPP_NAME: "raju-dotnetcore-app" 
   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.x'           # set this to the dot net version to use

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt-get update; 
          sudo apt-get install -y apt-transport-https && 
          sudo apt-get update && \
          sudo apt-get install -y dotnet-sdk-3.1
          sudo apt-get install aspnetcore-runtime-3.1
      - name: Dotnet verion
        run: dotnet --version
      
      - name: Generate webapp
        run: dotnet new webapp -n AspNetCoreDemo -o firstwebapp 
        
      - name: Copy Dotnet code to root
        run: |
          mv firstwebapp/* .
          rm -rf firstwebapp
      
      - name: List files
        run: ls
          
      - name: Build Dotnet app
        run: sudo dotnet build --configuration Release
        
      - name: List files
        run: ls
  
      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
#       - uses: azure/login@v1
#         with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
#       - name: 'Deploy using webapps-deploy'
#         id: deploy-to-webapp
#         uses: Azure/webapps-deploy@v2
#         with: 
#           app-name: ${{ env.AZURE_WEBAPP_NAME }}
#           package: .

